/**
 * Regenerates src/data/strokeDataExpanded.ts — the offline stroke-vector bundle.
 *
 * Usage (from the project root):
 *   bun scripts/fetchStrokes.ts
 *
 * Fetches hanzi-writer-data for every character in CHARACTERS_DATABASE that is not
 * already in the hand-curated CORE_STROKES map, so the writing canvas, the stroke
 * animator and dictation keep working with no network at all.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { CHARACTERS_DATABASE } from '../src/data/chineseData';
import { CORE_STROKES, type HanziCharData } from '../src/data/strokeData';

const CDN = 'https://cdn.jsdelivr.net/npm/hanzi-writer-data@2.0';
// Run from the project root (bun scripts/fetchStrokes.ts).
const OUT = resolve(process.cwd(), 'src/data/strokeDataExpanded.ts');
const CONCURRENCY = 6;

async function fetchChar(char: string, attempt = 1): Promise<HanziCharData | null> {
  try {
    const res = await fetch(`${CDN}/${encodeURIComponent(char)}.json`);
    if (!res.ok) return null;
    return (await res.json()) as HanziCharData;
  } catch {
    if (attempt < 3) {
      await new Promise((r) => setTimeout(r, 400 * attempt));
      return fetchChar(char, attempt + 1);
    }
    return null;
  }
}

const wanted = CHARACTERS_DATABASE.map((c) => c.character).filter((char) => !CORE_STROKES[char]);
console.log(`Fetching stroke data for ${wanted.length} character(s) not in CORE_STROKES...`);

const found: [string, HanziCharData][] = [];
const failed: string[] = [];

for (let i = 0; i < wanted.length; i += CONCURRENCY) {
  const batch = wanted.slice(i, i + CONCURRENCY);
  const results = await Promise.all(batch.map((char) => fetchChar(char)));
  results.forEach((data, index) => {
    const char = batch[index];
    if (data && Array.isArray(data.strokes) && data.strokes.length > 0) {
      found.push([char, data]);
    } else {
      failed.push(char);
    }
  });
  console.log(`  ${Math.min(i + CONCURRENCY, wanted.length)}/${wanted.length} done`);
}

const body = found
  .map(([char, data]) => `  ${JSON.stringify(char)}: ${JSON.stringify(data)},`)
  .join('\n');

const file = `// AUTO-GENERATED by scripts/fetchStrokes.ts — do not edit by hand.
// Re-run \`bun scripts/fetchStrokes.ts\` after adding characters to the data banks.
// Bundling these vectors keeps the writing canvas and dictation offline-capable.
import type { HanziCharData } from './strokeData';

export const EXPANDED_STROKES: Record<string, HanziCharData> = {
${body}
};
`;

writeFileSync(OUT, file, 'utf8');
console.log(`Wrote ${found.length} character(s) to ${OUT}`);
if (failed.length > 0) {
  console.error(`Failed to fetch: ${failed.join('')}`);
  process.exit(1);
}
